structure(list(I_D = c(10236L, 10235L, 10237L, 10238L, 10239L
), FLAG_TSUNAMI = c(NA, "Tsu", NA, NA, NA), YEAR = c(1933L, 2017L, 
2017L, 2017L, 2017L), MONTH = c(11L, 1L, 2L, 2L, 3L), DAY = c(20L, 
22L, 7L, 10L, 13L), HOUR = c(23L, 4L, 22L, 14L, 14L), MINUTE = c(21L, 
30L, 3L, 3L, 19L), SECOND = c(" 35.5", " 56.0", " 56.0", " 43.0", 
"  6.0"), FOCAL_DEPTH = c(15L, 136L, 26L, 15L, 10L), EQ_PRIMARY = c(" 7.7", 
" 7.9", " 6.3", " 6.5", " 5.1"), EQ_MAG_MW = c(" 7.7", " 7.9", 
" 6.3", " 6.5", NA), EQ_MAG_MS = c(" 7.4", NA, NA, NA, NA), EQ_MAG_MB = c(NA, 
NA, NA, NA, " 5.1"), EQ_MAG_ML = c(NA_real_, NA_real_, NA_real_, 
NA_real_, NA_real_), EQ_MAG_MFA = c(NA_character_, NA_character_, 
NA_character_, NA_character_, NA_character_), EQ_MAG_UNK = c(NA_character_, 
NA_character_, NA_character_, NA_character_, NA_character_), 
    INTENSITY = c(NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
    NA_integer_), COUNTRY = c("CANADA", "PAPUA NEW GUINEA", "PAKISTAN", 
    "PHILIPPINES", "MYANMAR (BURMA)"), STATE = c(NA_character_, 
    NA_character_, NA_character_, NA_character_, NA_character_
    ), LOCATION_NAME = c("CANADA:  BAFFIN BAY", "PAPUA NEW GUINEA:  BOUGAINVILLE ISLAND", 
    "PAKISTAN:  PASNI", "PHILIPPINES: SURIGAO DEL NORTE", "MYANMAR (BURMA):  THARRAWADDY"
    ), LATITUDE = c("  73.122", "  -6.214", "  25.216", "   9.911", 
    "  17.415"), LONGITUDE = c("  -70.014", "  155.122", "   63.272", 
    "  125.461", "   95.999"), REGION_CODE = c(150L, 170L, 60L, 
    170L, 60L), DEATHS = c(NA, NA, NA, "       8", "       2"
    ), DEATHS_DESCRIPTION = c(NA, NA, NA, 1L, 1L), MISSING = c(NA_character_, 
    NA_character_, NA_character_, NA_character_, NA_character_
    ), MISSING_DESCRIPTION = c(NA_integer_, NA_integer_, NA_integer_, 
    NA_integer_, NA_integer_), INJURIES = c(NA, NA, NA, "       202", 
    "        36"), INJURIES_DESCRIPTION = c(NA, NA, NA, 3L, 1L
    ), DAMAGE_MILLIONS_DOLLARS = c(NA_character_, NA_character_, 
    NA_character_, NA_character_, NA_character_), DAMAGE_DESCRIPTION = c(NA, 
    1L, 1L, 2L, 1L), HOUSES_DESTROYED = c(NA, NA, NA, 215L, NA
    ), HOUSES_DESTROYED_DESCRIPTION = c(NA, NA, NA, 3L, 1L), 
    HOUSES_DAMAGED = c(NA, NA, NA, 3042L, NA), HOUSES_DAMAGED_DESCRIPTION = c(NA, 
    NA, 1L, 4L, 1L), TOTAL_DEATHS = c(NA, NA, NA, "       8", 
    "       2"), TOTAL_DEATHS_DESCRIPTION = c(NA, NA, NA, 1L, 
    1L), TOTAL_MISSING = c(NA_character_, NA_character_, NA_character_, 
    NA_character_, NA_character_), TOTAL_MISSING_DESCRIPTION = c(NA_character_, 
    NA_character_, NA_character_, NA_character_, NA_character_
    ), TOTAL_INJURIES = c(NA, NA, NA, 202L, 36L), TOTAL_INJURIES_DESCRIPTION = c(NA, 
    NA, NA, 3L, 1L), TOTAL_DAMAGE_MILLIONS_DOLLARS = c(NA_character_, 
    NA_character_, NA_character_, NA_character_, NA_character_
    ), TOTAL_DAMAGE_DESCRIPTION = c(NA, 1L, 1L, 2L, 1L), TOTAL_HOUSES_DESTROYED = c(NA, 
    NA, NA, 215L, NA), TOTAL_HOUSES_DESTROYED_DESCRIPTION = c(NA, 
    NA, NA, 3L, 1L), TOTAL_HOUSES_DAMAGED = c(NA, NA, NA, 3042L, 
    NA), TOTAL_HOUSES_DAMAGED_DESCRIPTION = c(NA, NA, 1L, 4L, 
    1L)), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-5L), spec = structure(list(cols = structure(list(I_D = structure(list(), class = c("collector_integer", 
"collector")), FLAG_TSUNAMI = structure(list(), class = c("collector_character", 
"collector")), YEAR = structure(list(), class = c("collector_integer", 
"collector")), MONTH = structure(list(), class = c("collector_integer", 
"collector")), DAY = structure(list(), class = c("collector_integer", 
"collector")), HOUR = structure(list(), class = c("collector_integer", 
"collector")), MINUTE = structure(list(), class = c("collector_integer", 
"collector")), SECOND = structure(list(), class = c("collector_character", 
"collector")), FOCAL_DEPTH = structure(list(), class = c("collector_integer", 
"collector")), EQ_PRIMARY = structure(list(), class = c("collector_character", 
"collector")), EQ_MAG_MW = structure(list(), class = c("collector_character", 
"collector")), EQ_MAG_MS = structure(list(), class = c("collector_character", 
"collector")), EQ_MAG_MB = structure(list(), class = c("collector_character", 
"collector")), EQ_MAG_ML = structure(list(), class = c("collector_double", 
"collector")), EQ_MAG_MFA = structure(list(), class = c("collector_character", 
"collector")), EQ_MAG_UNK = structure(list(), class = c("collector_character", 
"collector")), INTENSITY = structure(list(), class = c("collector_integer", 
"collector")), COUNTRY = structure(list(), class = c("collector_character", 
"collector")), STATE = structure(list(), class = c("collector_character", 
"collector")), LOCATION_NAME = structure(list(), class = c("collector_character", 
"collector")), LATITUDE = structure(list(), class = c("collector_character", 
"collector")), LONGITUDE = structure(list(), class = c("collector_character", 
"collector")), REGION_CODE = structure(list(), class = c("collector_integer", 
"collector")), DEATHS = structure(list(), class = c("collector_character", 
"collector")), DEATHS_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), MISSING = structure(list(), class = c("collector_character", 
"collector")), MISSING_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), INJURIES = structure(list(), class = c("collector_character", 
"collector")), INJURIES_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), DAMAGE_MILLIONS_DOLLARS = structure(list(), class = c("collector_character", 
"collector")), DAMAGE_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), HOUSES_DESTROYED = structure(list(), class = c("collector_integer", 
"collector")), HOUSES_DESTROYED_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), HOUSES_DAMAGED = structure(list(), class = c("collector_integer", 
"collector")), HOUSES_DAMAGED_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_DEATHS = structure(list(), class = c("collector_character", 
"collector")), TOTAL_DEATHS_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_MISSING = structure(list(), class = c("collector_character", 
"collector")), TOTAL_MISSING_DESCRIPTION = structure(list(), class = c("collector_character", 
"collector")), TOTAL_INJURIES = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_INJURIES_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_DAMAGE_MILLIONS_DOLLARS = structure(list(), class = c("collector_character", 
"collector")), TOTAL_DAMAGE_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_HOUSES_DESTROYED = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_HOUSES_DESTROYED_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_HOUSES_DAMAGED = structure(list(), class = c("collector_integer", 
"collector")), TOTAL_HOUSES_DAMAGED_DESCRIPTION = structure(list(), class = c("collector_integer", 
"collector"))), .Names = c("I_D", "FLAG_TSUNAMI", "YEAR", "MONTH", 
"DAY", "HOUR", "MINUTE", "SECOND", "FOCAL_DEPTH", "EQ_PRIMARY", 
"EQ_MAG_MW", "EQ_MAG_MS", "EQ_MAG_MB", "EQ_MAG_ML", "EQ_MAG_MFA", 
"EQ_MAG_UNK", "INTENSITY", "COUNTRY", "STATE", "LOCATION_NAME", 
"LATITUDE", "LONGITUDE", "REGION_CODE", "DEATHS", "DEATHS_DESCRIPTION", 
"MISSING", "MISSING_DESCRIPTION", "INJURIES", "INJURIES_DESCRIPTION", 
"DAMAGE_MILLIONS_DOLLARS", "DAMAGE_DESCRIPTION", "HOUSES_DESTROYED", 
"HOUSES_DESTROYED_DESCRIPTION", "HOUSES_DAMAGED", "HOUSES_DAMAGED_DESCRIPTION", 
"TOTAL_DEATHS", "TOTAL_DEATHS_DESCRIPTION", "TOTAL_MISSING", 
"TOTAL_MISSING_DESCRIPTION", "TOTAL_INJURIES", "TOTAL_INJURIES_DESCRIPTION", 
"TOTAL_DAMAGE_MILLIONS_DOLLARS", "TOTAL_DAMAGE_DESCRIPTION", 
"TOTAL_HOUSES_DESTROYED", "TOTAL_HOUSES_DESTROYED_DESCRIPTION", 
"TOTAL_HOUSES_DAMAGED", "TOTAL_HOUSES_DAMAGED_DESCRIPTION")), 
    default = structure(list(), class = c("collector_guess", 
    "collector"))), .Names = c("cols", "default"), class = "col_spec"), .Names = c("I_D", 
"FLAG_TSUNAMI", "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND", 
"FOCAL_DEPTH", "EQ_PRIMARY", "EQ_MAG_MW", "EQ_MAG_MS", "EQ_MAG_MB", 
"EQ_MAG_ML", "EQ_MAG_MFA", "EQ_MAG_UNK", "INTENSITY", "COUNTRY", 
"STATE", "LOCATION_NAME", "LATITUDE", "LONGITUDE", "REGION_CODE", 
"DEATHS", "DEATHS_DESCRIPTION", "MISSING", "MISSING_DESCRIPTION", 
"INJURIES", "INJURIES_DESCRIPTION", "DAMAGE_MILLIONS_DOLLARS", 
"DAMAGE_DESCRIPTION", "HOUSES_DESTROYED", "HOUSES_DESTROYED_DESCRIPTION", 
"HOUSES_DAMAGED", "HOUSES_DAMAGED_DESCRIPTION", "TOTAL_DEATHS", 
"TOTAL_DEATHS_DESCRIPTION", "TOTAL_MISSING", "TOTAL_MISSING_DESCRIPTION", 
"TOTAL_INJURIES", "TOTAL_INJURIES_DESCRIPTION", "TOTAL_DAMAGE_MILLIONS_DOLLARS", 
"TOTAL_DAMAGE_DESCRIPTION", "TOTAL_HOUSES_DESTROYED", "TOTAL_HOUSES_DESTROYED_DESCRIPTION", 
"TOTAL_HOUSES_DAMAGED", "TOTAL_HOUSES_DAMAGED_DESCRIPTION"))
